[TAKS][WIP] Drop ddev configuration
FriendsOfTYPO3/tea pull request #1063
Opened 2023-12-15 12:17 UTC by lukaszuznanski

Resolves: #971

To be merged after runTests.sh implementation

2023-12-15 13:04 UTC, oliverklee commented on Documentation/Running.rst
> -You can run :bash:`composer` (or :bash:`ddev composer`) to display a list of all available
We could mention `runTests.sh composer` here.

2024-04-01 09:37 UTC, oliverklee commented
We now have a workable `runTests.sh`. Should we resurrect this PR?

2024-04-01 09:39 UTC, oliverklee commented
I think this deserves an entry in the changelog. What do you think?

2024-04-02 09:15 UTC, lukaszuznanski commented
> I think this deserves an entry in the changelog. What do you think?

Definitely. Will add and resolve conflicts

2024-04-14 11:12 UTC, oliverklee commented
Ping - let's get this in!

2024-04-15 12:46 UTC, oliverklee requested changes

2024-04-15 12:46 UTC, oliverklee commented on CHANGELOG.md
> +- Drop ddev configuration in favor of runTests.sh (#1063)
This needs to go into the current milestone, and it should be on top of the "Removed" section.

Also:
```suggestion
- Drop DDEV configuration in favor of `runTests.sh` (#1063)
```

2024-04-15 16:21 UTC, oliverklee approved these changes

2024-04-15 16:22 UTC, merged