[TASK] Move pph sniff to build dir
FriendsOfTYPO3/tea pull request #1357
Opened 2024-07-07 23:12 UTC by lukaszuznanski

Part of: https://github.com/FriendsOfTYPO3/tea/issues/1186

2024-07-08 07:41 UTC, oliverklee requested changes
We also need to adapt `.gitattributes` and the `prepare-release` Composer script.

2024-07-08 08:19 UTC, oliverklee requested changes

2024-07-08 08:19 UTC, oliverklee commented on composer.json
> +		"ci:php:sniff": "phpcs --standard=Build/phpcs/phpcs.xml Classes Configuration Tests",
We also need to adapt the `fix:php:sniff` Composer script accordingly.

2024-07-08 09:17 UTC, lukaszuznanski commented
> We also need to adapt `.gitattributes` and the `prepare-release` Composer script.

We remove whole `Build` dir, so only .gitattributes needs to be adapted.

2024-07-08 10:33 UTC, oliverklee commented
> We remove whole `Build` dir, so only `.gitattributes` needs to be adapted.

I was thinking of removing [this line](https://github.com/FriendsOfTYPO3/tea/blob/main/composer.json#L200) that removes a file that will no longer exist after this PR:

```
"rm phpcs.xml",
```

Am I missing something here?

2024-07-08 10:38 UTC, lukaszuznanski commented
> > We remove whole `Build` dir, so only `.gitattributes` needs to be adapted.
> 
> I was thinking of removing [this line](https://github.com/FriendsOfTYPO3/tea/blob/main/composer.json#L200) that removes a file that will no longer exist after this PR:
> 
> ```
> "rm phpcs.xml",
> ```
> 
> Am I missing something here?

Yes, that's correct, that needs to be removed.

2024-09-17 09:33 UTC, oliverklee requested changes

2024-09-17 09:33 UTC, oliverklee commented on composer.json
> +		"ci:php:sniff": "phpcs --standard=Build/php/phpcs.xml Classes Configuration Tests",
```suggestion
		"ci:php:sniff": "phpcs --standard=Build/phpcs/phpcs.xml Classes Configuration Tests",
```

2024-09-17 09:41 UTC, oliverklee approved these changes

2024-09-17 09:41 UTC, merged