[TASK] Add two new ISSUE_TEMPLATES, feature and task
FriendsOfTYPO3/tea pull request #1446
Opened 2024-09-04 10:30 UTC by linxpinx

2024-09-05 10:37 UTC, oliverklee requested changes
Looks generally good to me. I propose we also add a section "Additional information" below.

2024-09-05 11:49 UTC, oliverklee requested changes

2024-09-05 11:49 UTC, oliverklee commented on .github/ISSUE_TEMPLATE/feature.md
> +You can add any useful informations here, e.g. links, tipps ect.
```suggestion
Anything else that would be helpful to know to implement this feature.
```

2024-09-05 11:49 UTC, oliverklee commented on .github/ISSUE_TEMPLATE/task.md
> +You can add any useful informations here, e.g. links, tipps ect.
```suggestion
Anything else that would be helpful to know to complete this task.
```

2024-09-06 11:49 UTC, oliverklee approved these changes
Looks good to me. @DanielSiepmann @lukaszuznanski Could you also please have a look? Thanks!

2024-09-07 10:32 UTC, lukaszuznanski approved these changes

2024-09-07 10:33 UTC, merged