[TASK] Add php.ini from development
FriendsOfTYPO3/tea pull request #1461
Opened 2024-09-17 12:02 UTC by linxpinx

Fixed #1214

2024-09-17 12:12 UTC, oliverklee requested changes
With this, the CI build is failing:

jobs:build-composer-dependencies config contains unknown keys: volumes

https://git.typo3.org/qa/example-extension/-/pipelines/66001

2024-09-17 12:12 UTC, oliverklee commented on .gitlab/pipeline/ci/php.ini
> +sendmail_path="/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025"
We're not using Mailpit in GitLab CI (and also not on GitHub Actions), so this line doesn't look right.

2024-09-17 12:12 UTC, oliverklee commented on .gitlab/pipeline/jobs/.default.yml
> +    - ../ci/php.ini:/usr/local/etc/php/php.ini
There should always be a trailing LF after the last line in a file.

2024-09-17 12:46 UTC, linxpinx commented
I have updated the PR can you review again? @oliverklee @lukaszuznanski

2024-10-02 14:26 UTC, closed without merging

2024-10-02 14:27 UTC, linxpinx commented
I had to close this PR cause only PR created after 1.10.2024 and created with my Github Account will be seen by Hacktober.com