[TASK] Make records hidable and timeable
FriendsOfTYPO3/tea pull request #735
Opened 2023-01-24 21:37 UTC by lukaszuznanski

2023-02-21 22:11 UTC, lukaszuznanski commented
Different TCA needed for v11 and for v12

2023-03-01 17:28 UTC, oliverklee requested changes
I've manually tested this with my 11LTS testing installation:

- Hiding works if I use the "hide" icon in the list.
- When I edit a tea record in the DB, the fields hidden, starttime and endtime are not visible yet in the TCEforms.

So we'll also need to add those three fields to the `types` configuration.

2023-04-05 09:02 UTC, oliverklee requested changes
With this change, I get this exception when I try to edit a tea record in the BE:

> Item 0 of field hidden of TCA table tx_tea_domain_model_product_tea has no label

2023-04-05 09:20 UTC, lukaszuznanski commented
@oliverklee ok, so it's different for v12 and for v11, I have to adjust configuration. It works fine on v12.

2023-04-05 11:57 UTC, oliverklee requested changes

2023-04-05 11:57 UTC, oliverklee commented on Configuration/TCA/tx_tea_domain_model_product_tea.php
> +            ],
This now causes the toggle checkbox to work in inverse. With this setting, the record is visible for me:

![grafik](https://user-images.githubusercontent.com/765746/230072997-eb121691-8763-446f-ace9-0af79f79e0ff.png)

2023-04-05 11:57 UTC, oliverklee commented on Configuration/TCA/tx_tea_domain_model_product_tea.php
> +            ],
This is what the TCA for core records looks like in V11:

```
        'hidden' => [
            'exclude' => true,
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.enabled',
            'config' => [
                'type' => 'check',
                'renderType' => 'checkboxToggle',
                'items' => [
                    [
                        0 => '',
                        'invertStateDisplay' => true,
                    ],
                ],
            ],
        ],
```

2023-04-05 11:57 UTC, oliverklee commented on Configuration/TCA/tx_tea_domain_model_product_tea.php
> +            ],
Strange, this is the same as our code. I don't understand this.

2023-05-03 11:17 UTC, oliverklee commented
Testing in 11LTS, the "hide" toggle still is the wrong way around.

2023-05-03 11:19 UTC, oliverklee requested changes

2023-05-03 11:19 UTC, oliverklee commented on Configuration/TCA/tx_tea_domain_model_product_tea.php
> +                        'invertStateDisplay' => true,
Ah, we also need this added after line 136:

```
'invertStateDisplay' => true,
```

2023-05-13 19:51 UTC, oliverklee commented
This still needs the V11 fix, and also a reabse.

2023-06-17 08:27 UTC, oliverklee commented
@lukaszuznanski Do you have time to get this PR finished, or would you like me to take over?

2023-06-22 08:21 UTC, lukaszuznanski commented
@oliverklee if you have time to finish it, then go for it

2023-06-22 09:59 UTC, oliverklee commented
This looks really hard to rebase (also because we've merged `main` into this branch instead of rebasing it). I'm willing to do the V11 fixed, but don't have the time to first untangle the rebase mess right now.

2023-10-17 20:55 UTC, lukaszuznanski commented
I think it might be easier and faster to open new PR with those changes, will do.

2023-10-18 08:55 UTC, oliverklee commented
> I think it might be easier and faster to open new PR with those changes, will do.

Thanks!

2023-11-16 20:14 UTC, lukaszuznanski commented
Closed as there is new PR #989

2023-11-16 20:14 UTC, closed without merging