Add type coverage
FriendsOfTYPO3/tea pull request #889
Opened 2023-07-10 21:52 UTC by lukaszuznanski

Resolves: #830

2023-07-11 07:33 UTC, oliverklee commented on phpstan.neon
> +      property_type: 70
Let's go a lot higher!

2023-08-22 10:58 UTC, lukaszuznanski commented
Damn, I clicked on update branch and merged main into branch... sorry, let's check if there is way to disable this button, or change it's behavior. I will fix this error in functional tests.

2023-08-29 15:44 UTC, oliverklee commented
I've fixed this now:

```bash
git switch Feature/Add-type-coverage
git reset --hard a14f676
git rebase
git push -f
```

2023-10-17 21:19 UTC, lukaszuznanski commented
I changed it to 100, 100 and 95 for properties. We can update it to 100, but first we need to add property type. This should work for now. Let's do it in another PR.

2023-10-18 08:58 UTC, oliverklee approved these changes

2023-10-18 08:58 UTC, oliverklee requested changes
Looks good. It should get an entry in the changelog, though.

2023-10-23 08:48 UTC, oliverklee approved these changes

2023-10-23 08:48 UTC, merged