[TASK] Use own configuration files for tests
FriendsOfTYPO3/tea pull request #952
Opened 2023-10-17 21:09 UTC by lukaszuznanski

Resolves: #902

2023-10-18 08:57 UTC, oliverklee requested changes

2023-10-18 08:57 UTC, oliverklee commented on Tests/Functional/FunctionalTests.xml
> +<phpunit
AFAIK, the PHPUnit configuration (at least as written by PHPUnit) contains the XML prologue and the schema information:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.6/phpunit.xsd"
```

2023-10-23 08:42 UTC, oliverklee requested changes

2023-10-23 08:42 UTC, oliverklee commented on Tests/Unit/UnitTests.xml
> +        <!-- @todo: change tag to 'include' when TF requires phpunit > 9 -->
We're already using PHPUnit 9. So we should witch to `coverage` and `include` here.

2023-10-25 17:08 UTC, oliverklee approved these changes

2023-10-25 17:08 UTC, merged

2023-12-19 07:38 UTC, sbuerk commented
@oliverklee @lukaszuznanski 

Little bit late. TBH the bootstraps should also not be used from the the `typo3/testing-framework` vendor folder and copied to the project.

The background is, that there are scenarious where it's needed to make some changes based on the project/extension.

Beside this, the chosen location is kind of flattered. Configuration for all tools should be collected in one place and not distributed throughout a lot of places (and not the root folder)
to have a clean and "one place" to look it up. But that is maybe more a personally flavour - where I highly disagree to take this places as `best practice`.

2023-12-19 08:39 UTC, oliverklee commented
Thanks, I've created #1082 for moving these files.